### ISSUE TITLE
Support for Witcher 3 Next-Gen update

### ISSUE THREAD

**Issue by Traderain** [WolvenKit/WolvenKit-7#12]
**Is your feature request related to a problem? Please describe.**
Once the update drops I would like to keep using W3 Wkit.

**Describe the solution you'd like**
Working wkit.

**Describe alternatives you've considered**
Hex editor which is not ideal.

**Additional context**
Pull reqest #71

**Comment by K0stov** [comment]
Looking forward to this!

**Comment by nikich340** [comment]
> Looking forward to this!
https://github.com/WolvenKit/WolvenKit-7/releases/tag/v7.1.0-nge
