### ISSUE TITLE
Stuck at opening novigrad.w2w

### ISSUE THREAD

**Issue by NewKidHere** [WolvenKit/WolvenKit-7#22]
**Describe the bug**
Endless loading at clayerinfo 18125

**To Reproduce**
1. open novigrad.w2w
2. loading stuck at clayerinfo 18125

**Expected behavior**
Loading a w2w file inside wolvenkit for edit

**Screenshots**
![noviw2w](https://user-images.githubusercontent.com/77133304/208464243-cd150c50-064f-46dd-bee4-7b14c68d88fa.PNG)

**Desktop (please complete the following information):**
- windows 11

**Comment by Traderain** [comment]
Seems to be working with latest. Please reopen if needed.
