### ISSUE TITLE
Adding a redswf file from asset browser creates an empty file

### ISSUE THREAD

**Issue by rasitayaz** [WolvenKit/WolvenKit-7#29]
**Describe the bug**
I'm trying to import redswf files to my mod so that I can decompile and edit them. But when I add any redswf file to project using asset browser, it just creates an empty file at the selected redswf's path.

The weird thing is, I was able to get all the redswf files with their contents using "Game > Unbundle Game" from top menu. But adding redswf files from asset browser even after unbundling the game still behaves the same. I'm currently adding redswf files to my project manually by copying the files from unbundled game folder to my project folders.

**To Reproduce**
I'm not sure how this issue can be reproduced but here are my specs:

Windows 10 64 bit
Witcher 3 v4.01
ModKit v1.3
WolvenKit v7.1.0 (also tried some nightly versions)

**Expected behavior**
I expect to see redswf files being added from asset browser to my project with their content.

**Screenshots**
![image](https://user-images.githubusercontent.com/45076094/216809497-60ca5016-a623-44dc-b4cf-93f376916943.png) ![image1](https://user-images.githubusercontent.com/45076094/216809502-ed7fada3-5b3e-42ea-a77e-945e1d4bdea4.png)

**Comment by nikich340** [comment]
If file size is null, then you have updated with wkit installed for old game version. Remove old wkit and install/setup it again.

**Comment by rasitayaz** [comment]
The issue seems to be fixed with [version 7.2.0](https://github.com/WolvenKit/WolvenKit-7/releases).
